name: distribuidoragua
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.8.0
  cloud_firestore: ^4.6.0

  # State Management - MVVM
  provider: ^6.1.1

  # Responsive Design
  flutter_screenutil: ^5.9.0

  # Navigation
  go_router: ^12.1.3

  # Utils
  intl: ^0.19.0

  # URL Launcher
  url_launcher: ^6.2.2

  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.12.0
  
  # Excel Generation
  excel: ^4.0.2
  
  # File System Access
  path_provider: ^2.1.2
  permission_handler: ^11.3.0

  # Cupertino Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

# Configuración del splash screen
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/iconoApp.png
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  fullscreen: true

# Configuración del icono de la aplicación
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/iconoApp.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/iconoApp.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/iconoApp.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/iconoApp.png"
